In [1]:
import pandas as pan

parts_df = pan.read_csv("../data/experimental2/Copie de OPTIMACFORM - participants.csv")
f1_df = pan.read_csv("../data/experimental2/Copie de OPTIMACFORM - feedbacks_1.csv")
m0_df = pan.read_csv("../data/experimental2/Copie de OPTIMACFORM - motivations_0.csv")
m1_df = pan.read_csv("../data/experimental2/Copie de OPTIMACFORM - motivations_1.csv")
f0_df = pan.read_csv("../data/experimental2/Copie de OPTIMACFORM - feedbacks_0.csv")
sugg_df = pan.read_csv("../data/experimental2/Copie de OPTIMACFORM - suggestions.csv")

In [2]:
polluted_data = [62,67, 84,82]

def filter(df):
    return df[~df["n"].isin(polluted_data)]

parts_df

,Date,n,age,gender,category,self_eval
0,04-12-2025 16:53:00,1,entre 18 et 25 ans,Masculin,Agriculteurs/agricultrices exploitant.e.s,Amateur.e : Vous êtes sensible à ces sujets ma...
1,04-12-2025 21:30:32,2,entre 18 et 25 ans,Masculin,Employé.e.s,Amateur.e : Vous êtes sensible à ces sujets ma...
2,04-12-2025 22:50:30,3,entre 18 et 25 ans,Feminin,Autres personnes sans activités professionnell...,Amateur.e : Vous êtes sensible à ces sujets ma...
3,04-12-2025 22:50:43,4,entre 18 et 25 ans,Feminin,Autres personnes sans activités professionnell...,Amateur.e : Vous êtes sensible à ces sujets ma...
4,04-12-2025 22:52:05,5,entre 18 et 25 ans,Masculin,Cadres et professions intellectuelles supérieures,Connaisseur.euse : Vous êtes sensible à ces su...
...,...,...,...,...,...,...
123,11-12-2025 08:10:03,124,entre 18 et 25 ans,Feminin,Autres personnes sans activités professionnell...,Amateur.e : Vous êtes sensible à ces sujets ma...
124,11-12-2025 08:37:22,125,entre 41 et 65 ans,Feminin,Cadres et professions intellectuelles supérieures,Expert.e : Vous travaillez dans le domaine de ...
125,11-12-2025 14:14:10,126,66 ans et plus,Masculin,Cadres et professions intellectuelles supérieures,Expert.e : Vous travaillez dans le domaine de ...
126,16-12-2025 07:09:04,127,entre 18 et 25 ans,Masculin,Autres personnes sans activités professionnell...,Amateur.e : Vous êtes sensible à ces sujets ma...
127,18-12-2025 08:29:44,128,entre 26 et 40 ans,Feminin,Cadres et professions intellectuelles supérieures,Expert.e : Vous travaillez dans le domaine de ...

In [7]:
n_0  = filter(f0_df)["n"].nunique()
n_1  = filter(f1_df)["n"].nunique()

filtered_parts_0 = filter(parts_df)[parts_df["n"].isin(filter(f1_df)["n"])]
filtered_parts_0.groupby(["gender "]).count()

/tmp/ipykernel_790/1189142686.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  filtered_parts_0 = filter(parts_df)[parts_df["n"].isin(filter(f1_df)["n"])]

                    Date   n  age   category  self_eval
gender
Feminin               34  34    34        34         34
Masculin              35  35    35        35         35
Ne se prononce pas     2   2     2         2          2

In [6]:
n_0,n_1

(73, 71)